package com.campusfire.inspection;
import com.campusfire.audit.AuditService; import com.campusfire.auth.*; import com.campusfire.common.api.ApiResponse; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/inspection-risks") public class InspectionRiskController {
 private final JdbcTemplate db; private final AuthService auth; private final AuditService audit;
 public InspectionRiskController(JdbcTemplate db,AuthService auth,AuditService audit){this.db=db;this.auth=auth;this.audit=audit;}
 @GetMapping public ApiResponse<?> list(@RequestParam(required=false) String status,Authentication a){requireAdmin(a);return ApiResponse.success(db.queryForList("SELECT r.*,u.display_name AS inspector,v.display_name AS reviewer FROM inspection_risk_flag r JOIN app_user u ON u.id=r.user_id LEFT JOIN app_user v ON v.id=r.reviewed_by WHERE (? IS NULL OR r.status=?) ORDER BY CASE WHEN r.status='OPEN' THEN 0 ELSE 1 END,r.created_at DESC",status,status));}
 @PostMapping("/{id}/review") public ApiResponse<?> review(@PathVariable long id,@RequestBody Review r,Authentication a){AuthenticatedUser u=requireAdmin(a);if(r.status==null||r.status.trim().isEmpty())throw new IllegalArgumentException("请选择处理状态");int n=db.update("UPDATE inspection_risk_flag SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status='OPEN'",r.status,u.getId(),id);if(n==0)throw new IllegalArgumentException("风险标记不存在或已处理");audit.record(u.getId(),"INSPECTION_RISK_REVIEW","INSPECTION_RISK",String.valueOf(id),Collections.singletonMap("status",r.status));return ApiResponse.success(Collections.singletonMap("reviewed",true));}
 @DeleteMapping("/{id}") public ApiResponse<?> delete(@PathVariable long id,Authentication a){AuthenticatedUser u=requireAdmin(a);int n=db.update("DELETE FROM inspection_risk_flag WHERE id=?",id);if(n==0)throw new IllegalArgumentException("风险标记不存在");audit.record(u.getId(),"INSPECTION_RISK_DELETE","INSPECTION_RISK",String.valueOf(id),null);return ApiResponse.success(Collections.singletonMap("deleted",true));}
 private AuthenticatedUser requireAdmin(Authentication a){AuthenticatedUser u=auth.loadCurrentUser(a.getName());if(!"ADMIN".equals(u.getRoleCode()))throw new AccessDeniedException("仅管理员可以查看风险标记");return u;} public static class Review{public String status;}
}
