CREATE TABLE inspection_photo (
    id VARCHAR(36) NOT NULL,
    session_id VARCHAR(36) NOT NULL,
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    capture_source VARCHAR(32) NOT NULL,
    client_captured_at DATETIME(3) NOT NULL,
    device_id VARCHAR(128) NOT NULL,
    latitude DECIMAL(10,7) NOT NULL,
    longitude DECIMAL(10,7) NOT NULL,
    received_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_photo_session (session_id),
    KEY idx_photo_task (task_id),
    KEY idx_photo_sha256 (sha256),
    CONSTRAINT fk_photo_session FOREIGN KEY (session_id) REFERENCES inspection_session(id),
    CONSTRAINT fk_photo_task FOREIGN KEY (task_id) REFERENCES inspection_task(id),
    CONSTRAINT fk_photo_user FOREIGN KEY (user_id) REFERENCES app_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡检现场实时照片留痕';
