package com.campusfire.facility;
import com.campusfire.audit.AuditService; import com.campusfire.auth.*; import com.campusfire.common.api.ApiResponse; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import javax.validation.constraints.NotBlank; import java.util.*;
@RestController @RequestMapping("/facility-suggestions") public class FacilitySuggestionController {
 private final JdbcTemplate db; private final AuthService auth; private final AuditService audit;
 public FacilitySuggestionController(JdbcTemplate db,AuthService auth,AuditService audit){this.db=db;this.auth=auth;this.audit=audit;}
 @GetMapping public ApiResponse<?> list(@RequestParam(required=false) String status){return ApiResponse.success(db.queryForList("SELECT s.*,f.facility_no,f.name,f.campus,f.building,f.floor FROM facility_action_suggestion s JOIN facility f ON f.id=s.facility_id WHERE (? IS NULL OR s.status=?) ORDER BY CASE WHEN s.status='OPEN' THEN 0 ELSE 1 END,s.created_at DESC",status,status));}
 @PostMapping public ApiResponse<?> create(@RequestBody Request r,Authentication a){AuthenticatedUser u=current(a);if(!"ADMIN".equals(u.getRoleCode()))throw new AccessDeniedException("仅管理员可以创建更新或报废建议");if(r.facilityId==null||r.suggestionType==null||r.reason==null||r.reason.trim().isEmpty())throw new IllegalArgumentException("设施、建议类型和依据不能为空");db.update("INSERT INTO facility_action_suggestion(facility_id,suggestion_type,reason) VALUES(?,?,?)",r.facilityId,r.suggestionType,r.reason.trim());audit.record(u.getId(),"FACILITY_SUGGESTION_CREATE","FACILITY",String.valueOf(r.facilityId),Collections.singletonMap("type",r.suggestionType));return ApiResponse.success(Collections.singletonMap("saved",true));}
 @PostMapping("/{id}/action") public ApiResponse<?> action(@PathVariable long id,@RequestBody Action r,Authentication a){AuthenticatedUser u=current(a);if(!"ADMIN".equals(u.getRoleCode()))throw new AccessDeniedException("仅管理员可以处理建议");if(r.status==null||r.status.trim().isEmpty()||r.note==null||r.note.trim().isEmpty())throw new IllegalArgumentException("处理状态和理由不能为空");Map<String,Object> s=db.queryForMap("SELECT facility_id,suggestion_type FROM facility_action_suggestion WHERE id=? AND status='OPEN'",id);db.update("UPDATE facility_action_suggestion SET status=?,action_note=?,action_by=?,action_at=NOW() WHERE id=? AND status='OPEN'",r.status,r.note.trim(),u.getId(),id);if("SCRAPPED".equals(r.status)||"RETIRED".equals(r.status))db.update("UPDATE facility SET lifecycle_status=? WHERE id=?",r.status,s.get("facility_id"));audit.record(u.getId(),"FACILITY_SUGGESTION_ACTION","FACILITY",String.valueOf(s.get("facility_id")),Collections.singletonMap("status",r.status));return ApiResponse.success(Collections.singletonMap("handled",true));}
 @DeleteMapping("/{id}") public ApiResponse<?> delete(@PathVariable long id,Authentication a){AuthenticatedUser u=current(a);if(!"ADMIN".equals(u.getRoleCode()))throw new AccessDeniedException("仅管理员可以删除建议");int n=db.update("DELETE FROM facility_action_suggestion WHERE id=? AND status='OPEN'",id);if(n==0)throw new IllegalArgumentException("建议不存在或已处理，不能删除");audit.record(u.getId(),"FACILITY_SUGGESTION_DELETE","FACILITY_SUGGESTION",String.valueOf(id),null);return ApiResponse.success(Collections.singletonMap("deleted",true));}
 private AuthenticatedUser current(Authentication a){return auth.loadCurrentUser(a.getName());} public static class Request{public Long facilityId;public String suggestionType;public String reason;} public static class Action{@NotBlank public String status;@NotBlank public String note;}
}
